version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sadok
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: nest
    volumes:
      - .dbata:/var/lib/postgres

  redis:
    image: redis:latest
    ports:
    - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025